# This is a TOML document.

title = "TOML Example"

[owner]
username = "Qboi123"
dob = 2004-03-04T21:32:00+01:00  # First class dates

[database]
server = "172.16.39.39"
ports = [ 25515 ]
connection_max = 20
enabled = true

[server]

  # Indentation (tabs and/or spaces) is allowed but not required
  [server.server]
  ip = "172.16.39.39"
  port = "25565"
  dc = ""

  [servers.query]
  ip = "172.16.39.39"
  port = "25575"
  dc = ""

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]